### ISSUE TITLE
"Colcon Build --symlink-install" Broke on latest commit

### ISSUE THREAD

**Issue by ajifoster3** [CoppeliaRobotics/simExtROS2Interface#13]
Error: 
`
--- stderr: sim_ros2_interface                             
/home/afoster2/Documents/sim_ros2_interface/src/ros_msg_builtin_io.cpp: In function ‘void read__bool(int, bool*, const ROS2ReadOptions*)’:
/home/afoster2/Documents/sim_ros2_interface/src/ros_msg_builtin_io.cpp:19:38: error: cannot convert ‘bool*’ to ‘simBool*’ {aka ‘unsigned char*’}
   19 |     if(sim::getStackBoolValue(stack, &v) == 1)
      |                                      ^~
      |                                      |
      |                                      bool*
In file included from /home/afoster2/Documents/sim_ros2_interface/build/sim_ros2_interface/generated/stubs.h:4,
                 from /home/afoster2/Documents/sim_ros2_interface/src/ros_msg_builtin_io.cpp:4:
/home/afoster2/Documents/CoppeliaSim_Edu_V4_4_0_rev0_Ubuntu20_04/programming/libPlugin/simPlusPlus/Lib.h:124:59: note:   initializing argument 2 of ‘simInt sim::getStackBoolValue(simInt, simBool*)’
  124 |     simInt getStackBoolValue(simInt stackHandle, simBool *boolValue);
      |                                                  ~~~~~~~~~^~~~~~~~~
gmake[2]: *** [CMakeFiles/simExtROS2.dir/build.make:213: CMakeFiles/simExtROS2.dir/src/ros_msg_builtin_io.cpp.o] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:164: CMakeFiles/simExtROS2.dir/all] Error 2
gmake: *** [Makefile:146: all] Error 2
`

**Comment by fferri** [comment]
HEAD is for developers.

You need to checkout the version tagged 'coppeliasim-v4.4.0-rev0'.
