### ISSUE TITLE
error: This project has asked CMake to find a package configuration file provided by "Python3", but CMake did not find one

### ISSUE THREAD

**Issue by zhongdian** [CoppeliaRobotics/simExtROS2Interface#6]
I cloned the relevant files according to the tutorial. When I compiled, an error message was displayed indicating that python3 is missing, but python3 is installed on my computer. How can I solve it? Can you help me?
![批注 2020-07-01 161842](https://user-images.githubusercontent.com/13184299/86220744-98c96980-bbb6-11ea-864d-e88d4b0cf741.png)
![批注 2020-07-01 161943](https://user-images.githubusercontent.com/13184299/86220804-b0a0ed80-bbb6-11ea-95a1-dd67768656f8.png)

**Comment by fferri** [comment]
Did you install cmake 3.16.3 or greater?

**Comment by fferri** [comment]
Can you please provide these additional details:

 - OS version (`lsb-release -a`)
 - cmake version (`cmake --version`)
 - output of `ls /usr/share/cmake*/Modules/FindPython*`
 - ROS distribution (`echo $ROS_DISTRO` after you have executed `source /opt/ros/....`)

**Comment by zhongdian** [comment]
Thank you for your reply. I am sorry for not providing complete information, here is what you need.
OS version : `Ubuntu 18.04.4 LTS`
cmake version : `3.10.2`
ouput : 
`/usr/share/cmake-3.10/Modules/FindPythonInterp.cmake`
`/usr/share/cmake-3.10/Modules/FindPythonLibs.cmake`
ROS distribution: `dashing`

**Comment by fferri** [comment]
`dashing` is not supported anymore. you need at least `foxy`.

You can upgrade cmake by using KitWare's apt repositories, but then you will probably encounter other build issues.
