### ISSUE TITLE
Unknown CMake command "coppeliasim_add_plugin".

### ISSUE THREAD

**Issue by alanxuefei** [CoppeliaRobotics/simExtROS2Interface#8]
Starting >>> sim_ros2_interface
--- stderr: sim_ros2_interface                         
CMake Error at CMakeLists.txt:86 (coppeliasim_add_plugin):
  Unknown CMake command "coppeliasim_add_plugin".

---
Failed   <<< sim_ros2_interface [3.04s, exited with code 1]

Summary: 0 packages finished [3.17s]
  1 package failed: sim_ros2_interface
  1 package had stderr output: sim_ros2_interface

**Comment by fferri** [comment]
Update [libPlugin](https://github.com/CoppeliaRobotics/libPlugin)

**Comment by alanxuefei** [comment]
I download the latest libPlugin and replace current libPlugin. 

The error becomes as below:

Starting >>> sim_ros2_interface
--- stderr: sim_ros2_interface                         
CMake Error at /home/alan/Desktop/CoppeliaSim/programming/libPlugin/cmake/FindCoppeliaSim.cmake:206 (message):
  Failed reading plugin metadata (error in XML file?)
Call Stack (most recent call first):
  CMakeLists.txt:77 (coppeliasim_generate_stubs)


---
Failed   <<< sim_ros2_interface [8.66s, exited with code 1]

Summary: 0 packages finished [9.04s]
  1 package failed: sim_ros2_interface
  1 package had stderr output: sim_ros2_interface

**Comment by fferri** [comment]
I can't reproduce that.

Please show verbose build output, set `VERBOSE=1` and `MAKEFLAGS=-j1` env vars and add `--event-handlers console_direct+` and `--parallel-workers 1` options, e.g.:

```bash
VERBOSE=1 MAKEFLAGS=-j1 colcon build --symlink-install --event-handlers console_direct+ --parallel-workers 1
```

Also please post the content of `sim_ros2_interface/meta/callbacks.xml`

**Comment by alanxuefei** [comment]
The output is as below:

alan@ubuntu:~/dev_ws/src/sim_ros2_interface$ VERBOSE=1 MAKEFLAGS=-j1 colcon build --symlink-install --event-handlers console_direct+ --parallel-workers 1
Starting >>> sim_ros2_interface
Re-run cmake no build system arguments
-- Found ament_cmake: 0.9.7 (/home/alan/ros2_foxy/install/ament_cmake/share/ament_cmake/cmake)
-- Using PYTHON_EXECUTABLE: /usr/bin/python3           
-- Override CMake install command with custom implementation using symlinks instead of copying resources
-- Found ament_cmake_ros: 0.9.0 (/home/alan/ros2_foxy/install/ament_cmake_ros/share/ament_cmake_ros/cmake)
-- Found diagnostic_msgs: 2.0.3 (/home/alan/ros2_foxy/install/diagnostic_msgs/share/diagnostic_msgs/cmake)
-- Using all available rosidl_typesupport_c: rosidl_typesupport_fastrtps_c;rosidl_typesupport_introspection_c
-- Found rosidl_adapter: 1.1.0 (/home/alan/ros2_foxy/install/rosidl_adapter/share/rosidl_adapter/cmake)
-- Using all available rosidl_typesupport_cpp: rosidl_typesupport_fastrtps_cpp;rosidl_typesupport_introspection_cpp
-- Found geometry_msgs: 2.0.3 (/home/alan/ros2_foxy/install/geometry_msgs/share/geometry_msgs/cmake)
-- Found lifecycle_msgs: 1.0.0 (/home/alan/ros2_foxy/install/lifecycle_msgs/share/lifecycle_msgs/cmake)
-- Found map_msgs: 2.0.2 (/home/alan/ros2_foxy/install/map_msgs/share/map_msgs/cmake)
-- Found pendulum_msgs: 0.9.3 (/home/alan/ros2_foxy/install/pendulum_msgs/share/pendulum_msgs/cmake)
-- Found rosgraph_msgs: 1.0.0 (/home/alan/ros2_foxy/install/rosgraph_msgs/share/rosgraph_msgs/cmake)
-- Found shape_msgs: 2.0.3 (/home/alan/ros2_foxy/install/shape_msgs/share/shape_msgs/cmake)
-- Found stereo_msgs: 2.0.3 (/home/alan/ros2_foxy/install/stereo_msgs/share/stereo_msgs/cmake)
-- Found tf2_geometry_msgs: 0.13.7 (/home/alan/ros2_foxy/install/tf2_geometry_msgs/share/tf2_geometry_msgs/cmake)
-- Found eigen3_cmake_module: 0.1.1 (/home/alan/ros2_foxy/install/eigen3_cmake_module/share/eigen3_cmake_module/cmake)
-- Found rmw_implementation_cmake: 1.0.2 (/home/alan/ros2_foxy/install/rmw_implementation_cmake/share/rmw_implementation_cmake/cmake)
-- Using RMW implementation 'rmw_fastrtps_cpp' as default
-- Found trajectory_msgs: 2.0.3 (/home/alan/ros2_foxy/install/trajectory_msgs/share/trajectory_msgs/cmake)
-- Found visualization_msgs: 2.0.3 (/home/alan/ros2_foxy/install/visualization_msgs/share/visualization_msgs/cmake)
-- Found std_srvs: 2.0.3 (/home/alan/ros2_foxy/install/std_srvs/share/std_srvs/cmake)
-- Found example_interfaces: 0.9.0 (/home/alan/ros2_foxy/install/example_interfaces/share/example_interfaces/cmake)
-- Found image_transport: 2.3.0 (/opt/ros/foxy/share/image_transport/cmake)
-- CoppeliaSim: LIBPLUGIN_DIR: /home/alan/Desktop/CoppeliaSim/programming/libPlugin.
-- CoppeliaSim: COPPELIASIM_ROOT_DIR: /home/alan/Desktop/CoppeliaSim.
-- Found CoppeliaSim installation at /home/alan/Desktop/CoppeliaSim.
-- Checking CoppeliaSim header version...
-- CoppeliaSim headers version 4.1.0 rev1              
-- Found Boost: /usr/lib/x86_64-linux-gnu/cmake/Boost-1.71.0/BoostConfig.cmake (found version "1.71.0") found components: regex 
-- Found Boost: /usr/lib/x86_64-linux-gnu/cmake/Boost-1.71.0/BoostConfig.cmake (found version "1.71.0")  
-- Adding simStubsGen command...
-- Reading plugin metadata...                          
                                                       

   error: Python package "xmlschema" not found.
          Please install it, e.g.: python3 -m pip install xmlschema


CMake Error at /home/alan/Desktop/CoppeliaSim/programming/libPlugin/cmake/FindCoppeliaSim.cmake:206 (message):
  Failed reading plugin metadata (error in XML file?)
Call Stack (most recent call first):
  CMakeLists.txt:77 (coppeliasim_generate_stubs)


-- Configuring incomplete, errors occurred!
See also "/home/alan/dev_ws/src/sim_ros2_interface/build/sim_ros2_interface/CMakeFiles/CMakeOutput.log".
See also "/home/alan/dev_ws/src/sim_ros2_interface/build/sim_ros2_interface/CMakeFiles/CMakeError.log".
--- stderr: sim_ros2_interface                         
CMake Error at /home/alan/Desktop/CoppeliaSim/programming/libPlugin/cmake/FindCoppeliaSim.cmake:206 (message):
  Failed reading plugin metadata (error in XML file?)
Call Stack (most recent call first):
  CMakeLists.txt:77 (coppeliasim_generate_stubs)


---
Failed   <<< sim_ros2_interface [6.98s, exited with code 1]

Summary: 0 packages finished [7.22s]
  1 package failed: sim_ros2_interface
  1 package had stderr output: sim_ros2_interface


Callbacks.xml is as below.

[callbacks.zip](https://github.com/CoppeliaRobotics/simExtROS2Interface/files/5636955/callbacks.zip)

**Comment by fferri** [comment]
> error: Python package "xmlschema" not found.
> Please install it, e.g.: python3 -m pip install xmlschema

Ditto.

**Comment by alanxuefei** [comment]
It works. Thanks.

**Comment by fferri** [comment]
Now `xmlschema` is optional, as it is mostly useful to plugin developers.

You can pull latest version of libPlugin and remove xmlschema.

However, leaving it installed won't hurt.

**Comment by qingtian1771** [comment]
I don't know where I can put the libPlugin. Could you please privide the build command script?

I put the libPlugin at my_work_space/src like following, and use command "colcon build --symlink-install --cmake-args -DCMAKE_BUILD_TYPE=Release" to build.
I refered the link https://www.coppeliarobotics.com/helpFiles/en/ros2Tutorial.htm 
.
├── libPlugin
├── ros2_bubble_rob
└── sim_ros2_interface

And it give me following error:
<pre>CMake Error at CMakeLists.txt:56 (find_package):
  By not providing &quot;FindCoppeliaSim.cmake&quot; in CMAKE_MODULE_PATH this project
  has asked CMake to find a package configuration file provided by
  &quot;CoppeliaSim&quot;, but CMake did not find one.

  Could not find a package configuration file provided by &quot;CoppeliaSim&quot;
  (requested version 4.1.0.0) with any of the following names:

    CoppeliaSimConfig.cmake
    coppeliasim-config.cmake

  Add the installation prefix of &quot;CoppeliaSim&quot; to CMAKE_PREFIX_PATH or set
  &quot;CoppeliaSim_DIR&quot; to a directory containing one of the above files.  If
  &quot;CoppeliaSim&quot; provides a separate development package or SDK, be sure it
  has been installed.


---
Failed   &lt;&lt;&lt; sim_ros2_interface [1.42s, exited with code 1]

Summary: 2 packages finished [1.55s]
  1 package failed: sim_ros2_interface
  1 package had stderr output: sim_ros2_interface
</pre>

So what I should do, could you please help?

Thanks,
Regards!

**Comment by fferri** [comment]
libPlugin location is `$COPPELIASIM_ROOT_DIR/programming/libPlugin`

**Comment by qingtian1771** [comment]
Thanks!
And I remove libPlugin from my_work_space/src and build again, I got same error, should I change something in CMakeLists.txt of project sim_ros2_interface?
I change follow line from 
find_package(CoppeliaSim 4.1.0.0 REQUIRED)
to 
find_package(CoppeliaSim 4.1.0.1 REQUIRED)
according my CoppeliaSim version, but it seems no effect.

this is the build command
```
tq@tq-sy:~/code/ros2/vrep_ws$ export COPPELIASIM_ROOT_DIR=/home/tq/software/CoppeliaSim_Edu_V4_1_0_Ubuntu18_04
tq@tq-sy:~/code/ros2/vrep_ws$ ulimit -s unlimited
tq@tq-sy:~/code/ros2/vrep_ws$ colcon build --symlink-install --cmake-args -DCMAKE_BUILD_TYPE=Release
```
How to make it work?

**Comment by qingtian1771** [comment]
it seems there is no libsimExtROS2Interface.so in my COPPELIASIM_ROOT_DIR folder or sub folder, and I should build it first by myself, is it right?
And how can I build this lib, thanks!

**Comment by qingtian1771** [comment]
the problem maybe in "find_package(CoppeliaSim 4.1.0.1 REQUIRED)", because I didn't install CoppeliaSim, I just unzip and use it, how to make cmake to find CoppeliaSim? any idea?

**Comment by fferri** [comment]
So what output do you get from the following command?

    ls ${COPPELIASIM_ROOT_DIR}/programming/libPlugin/cmake

**Comment by qingtian1771** [comment]
> So what output do you get from the following command?
> 
> ```
> ls ${COPPELIASIM_ROOT_DIR}/programming/libPlugin/cmake
> ```

FindCoppeliaSim.cmake

**Comment by qingtian1771** [comment]
I made a little CMakeLists.txt as following to test.
```
cmake_minimum_required(VERSION 3.5)
project(test)

if(NOT LIBPLUGIN_DIR)
    if(DEFINED ENV{COPPELIASIM_ROOT_DIR})
        set(LIBPLUGIN_DIR $ENV{COPPELIASIM_ROOT_DIR}/programming/libPlugin)
    else()
        message(FATAL_ERROR "Environment variable COPPELIASIM_ROOT_DIR is not set")
    endif()
endif()
list(APPEND CMAKE_MODULE_PATH
    ${CMAKE_CURRENT_SOURCE_DIR}/cmake/modules
    ${LIBPLUGIN_DIR}/cmake)
    
message(${LIBPLUGIN_DIR})
message(${CMAKE_MODULE_PATH})


```
and the output is following after I use "cmake ." to build
<pre>/home/tq/software/CoppeliaSim_Edu_V4_1_0_Ubuntu18_04/programming/libPlugin
/home/tq/test/cmake_test/cmake/modules/home/tq/software/CoppeliaSim_Edu_V4_1_0_Ubuntu18_04/programming/libPlugin/cmake
-- Configuring done
-- Generating done
-- Build files have been written to: /home/tq/test/cmake_test
</pre>
And I found CMAKE_MODULE_PATH output is no seperation between two path, is this the problem?

**Comment by qingtian1771** [comment]
tq@tq-sy:~$ cmake --version
cmake version 3.19.4

CMake suite maintained and supported by Kitware (kitware.com/cmake).

**Comment by fferri** [comment]
> ```
> message(${LIBPLUGIN_DIR})
> message(${CMAKE_MODULE_PATH})
> ```
[...]
> And I found CMAKE_MODULE_PATH output is no seperation between two path, is this the problem?

I don't think so.
`CMAKE_MODULE_PATH` is a list. By passing `${CMAKE_MODULE_PATH}` to [`message()`](https://cmake.org/cmake/help/latest/command/message.html) you are actually passing multiple arguments to `message()`, and the behavior is clearly documented in the cmake manual:

> Record the specified message text in the log. If more than one message string is given, they are concatenated into a single message with no separator between the strings.

and it is exactly what you are seeing.

Try quoting `${CMAKE_MODULE_PATH}`, i.e.:

```
message("${CMAKE_MODULE_PATH}")
```

and you'll see the list separator.

**Comment by qingtian1771** [comment]
Yes, fferri, you are right. is seems CMAKE_MODULE_PATH have no problem, and I changed my CMakeLists.txt, add some findpackage, it works all right.

The CMakeLists.txt is here:

```
cmake_minimum_required(VERSION 3.5)
project(test)


if(NOT LIBPLUGIN_DIR)
    if(DEFINED ENV{COPPELIASIM_ROOT_DIR})
        set(LIBPLUGIN_DIR $ENV{COPPELIASIM_ROOT_DIR}/programming/libPlugin)
    else()
        message(FATAL_ERROR "Environment variable COPPELIASIM_ROOT_DIR is not set")
    endif()
endif()
list(APPEND CMAKE_MODULE_PATH
    ${CMAKE_CURRENT_SOURCE_DIR}/cmake/modules
    ${LIBPLUGIN_DIR}/cmake)
    
message(${LIBPLUGIN_DIR})
message("${CMAKE_MODULE_PATH}")

find_package(CoppeliaSim 4.1.0.1 REQUIRED)
find_package(Python3 REQUIRED COMPONENTS Interpreter)
find_package(Boost REQUIRED)

file(MAKE_DIRECTORY ${CMAKE_CURRENT_BINARY_DIR}/generated)
file(MAKE_DIRECTORY ${CMAKE_CURRENT_BINARY_DIR}/doc)

```
And the cmake output is here:
<pre><font color="#4E9A06"><b>tq@tq-sy</b></font>:<font color="#3465A4"><b>~/test/cmake_test</b></font>$ cmake .
-- The C compiler identification is GNU 9.3.0
-- The CXX compiler identification is GNU 9.3.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
/home/tq/software/CoppeliaSim_Edu_V4_1_0_Ubuntu18_04/programming/libPlugin
/home/tq/test/cmake_test/cmake/modules;/home/tq/software/CoppeliaSim_Edu_V4_1_0_Ubuntu18_04/programming/libPlugin/cmake
-- CoppeliaSim: LIBPLUGIN_DIR: /home/tq/software/CoppeliaSim_Edu_V4_1_0_Ubuntu18_04/programming/libPlugin.
-- CoppeliaSim: COPPELIASIM_ROOT_DIR: /home/tq/software/CoppeliaSim_Edu_V4_1_0_Ubuntu18_04.
-- Found CoppeliaSim installation at /home/tq/software/CoppeliaSim_Edu_V4_1_0_Ubuntu18_04.
-- Checking CoppeliaSim header version...
-- CoppeliaSim headers version 4.1.0 rev1
-- Found Git: /usr/bin/git (found version &quot;2.25.1&quot;) 
-- Found Python3: /usr/bin/python3.8 (found version &quot;3.8.5&quot;) found components: Interpreter 
-- Found Boost: /usr/lib/x86_64-linux-gnu/cmake/Boost-1.71.0/BoostConfig.cmake (found version &quot;1.71.0&quot;)  
-- Configuring done
-- Generating done
-- Build files have been written to: /home/tq/test/cmake_test
<font color="#4E9A06"><b>tq@tq-sy</b></font>:<font color="#3465A4"><b>~/test/cmake_test</b></font>$</pre>

So it seems the "cmake ." works all right, so it must be the "colcon build ..." problem.

Do you have any idea how to fix it?

**Comment by fferri** [comment]
No, the plugin builds fine with `colcon` (which is just a wrapper to `cmake`) on my machines. Must be something with your setup. Try starting from scratch (i.e. from an empty workspace), and see if you can reproduce the problem.

**Comment by qingtian1771** [comment]
Hi fferri, you are right again, thanks for your kindness and patient!

I did following:
```
mkdir -p vrep_ws_2/src
cd vrep_ws_2/src/
git clone --recursive https://github.com/CoppeliaRobotics/simExtROS2Interface.git sim_ros2_interface
cd ..
export COPPELIASIM_ROOT_DIR=/home/tq/software/CoppeliaSim_Edu_V4_1_0_Ubuntu18_04
ulimit -s unlimited
colcon build --symlink-install
```
and it give me this error:
```
Starting >>> sim_ros2_interface
--- stderr: sim_ros2_interface                         
CMake Error at CMakeLists.txt:86 (coppeliasim_add_plugin):
  Unknown CMake command "coppeliasim_add_plugin".


---
Failed   <<< sim_ros2_interface [2.49s, exited with code 1]

Summary: 0 packages finished [2.58s]
  1 package failed: sim_ros2_interface
  1 package had stderr output: sim_ros2_interface
```
And I replace libPlugin with new one, and build again, it finished with no error!
```
Starting >>> sim_ros2_interface
[Processing: sim_ros2_interface]                             
Finished <<< sim_ros2_interface [54.4s]                       

Summary: 1 package finished [54.5s]
```
And I found the lib libsimExtROS2.so in build dir, and I copy to CoppeliaSim_Edu_V4_1_0_Ubuntu18_04 folder, and start CoppeliaSim, and use "ros2 node list" to check node, the node "/sim_ros2_interface" appeared.

Thanks a lot, I should this earlier!
By the way, the name of ROS2 interface is libsimExtROS2.so, but the name in online help is libsimExtROS2Interface.so, I think it is a little mistake.

**Comment by ER-ROUGUI** [comment]
> Update [libPlugin](https://github.com/CoppeliaRobotics/libPlugin)

Hello the same probleme i got this error 

Starting >>> my_robot_controller
Starting >>> my_ur5_controller                    
Finished <<< my_ur5_controller [6.50s]                            
Starting >>> sim_ros2_interface
Finished <<< my_robot_controller [7.39s]                           
--- stderr: sim_ros2_interface                           
CMake Error at CMakeLists.txt:55 (message):
  Environment variable COPPELIASIM_ROOT_DIR is not set


---
Failed   <<< sim_ros2_interface [12.3s, exited with code 1]
                                 
Summary: 2 packages finished [22.2s]
  1 package failed: sim_ros2_interface
  1 package had stderr output: sim_ros2_interface

**Comment by fferri** [comment]
> Environment variable COPPELIASIM_ROOT_DIR is not set

you have to set it via `export COPPELIASIM_ROOT_DIR=/path/to/CoppeliaSim_V4_X_Y` prior to building the plugin.
